spring:
  cache:
    type: generic

  datasource:
    url: jdbc:mysql://localhost:3306/book_store
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: librarian
    password: Knowledge!sPower

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

memcached:
  host: localhost
  port: 11211

logging:
  level:
    org.springframework.cache: trace
    org.springframework.web: trace
    org.hibernate.sql: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
